#!/bin/bash
declare -a datasets=("ArrowHead" "Beef" "Coffee" "FaceFour" "Gun_Point" "OliveOil" "Plane" "Trace" "Wine")

mkdir -p results

for dataset in ${datasets[@]}; do
    bsub -R '(!gpu) span[hosts=1]' -G SEAS-Lab-Garnett -J "${dataset}" "./onerun $dataset"
done