#!/bin/bash
declare -a datasets=("BeetleFly" "Coffee" "Earthquakes" "Gun_Point" "Ham" "ItalyPowerDemand" "MoteStrain" "ShapeletSim" "WormsTwoClass")

mkdir -p results

for dataset in ${datasets[@]}; do
    bsub -R '(!gpu) span[hosts=1]' -G SEAS-Lab-Garnett -J "${dataset}" "./onerun $dataset"
done